### ISSUE TITLE
Cadence too high

### ISSUE THREAD

**Issue by jonathancolledge** [mrverrall/go-row-cycle#11]
Hi, this works really well except the cadence is seventy-something when I'm only at twenty something strokes per minute. I tried changing *3 to *1 in cpm.go, but clearly that isn't the bit I need to change! Can you help please?

**Comment by mrverrall** [comment]
Hi, assume this is for cycling (cpm = cycle power meter). I think you have the correct line,

https://github.com/mrverrall/go-row/blob/d6b59c233cb41705731dafe0bf2744945b2f4f0e/peripheral/cpm.go#L42

After a change to the code you'll need to ensure you recompile (go build) and that you are running the new binary. If you're running as a service this will mean copying to the correct path and restarting the service.

Hope that helps

**Comment by jonathancolledge** [comment]
Thanks! I'll give that a go.

**Comment by jonathancolledge** [comment]
Thanks, it works perfectly

**Comment by mrverrall** [comment]
no problem, glad you are finding this useful.
